---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: elasticsearch
  namespace: kubeaddons
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  chartReference:
    chart: stable/elasticsearch
    version: 1.26.2
    values: |
      ---
      client:
        heapSize: 1024m
        resources:
          limits:
            cpu: 500m
            memory: 2048Mi
          requests:
            cpu: 100m
            memory: 1536Mi
      master:
        updateStrategy:
          type: RollingUpdate
        heapSize: 1024m
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 250m
            memory: 1536Mi
      data:
        updateStrategy:
          type: RollingUpdate
        hooks:
          drain:
            enabled: false
        heapSize: 1536m
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
            memory: 4096Mi
          requests:
            cpu: 250m
            memory: 2048Mi
