---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: kommander
  namespace: kommander
  labels:
    kubeaddons.mesosphere.io/name: kommander
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  cloudProvider:
    aws: enabled
    docker: enabled
    none: enabled
  chartReference:
    chart: kommander
    repo: https://mesosphere.github.io/charts/stable
    version: 0.1.1
