---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: kommander
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: kommander
  annotations:
    appversion.kubeaddons.mesosphere.io: "1.24.2"
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: kommander
    repo: https://mesosphere.github.io/charts/stable
    version: 0.1.0
