---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: localvolumeprovisioner
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: localvolumeprovisioner
    kubeaddons.mesosphere.com/provides: storageclass
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  cloudProvider:
    aws: disabled
    docker: enabled
    none: enabled
  chartReference:
    chart: localvolumeprovisioner
    repo: https://mesosphere.github.io/charts/stable
    version: 0.1.1
