### DEPRECATED ###
# This Addon is deprecated in favor of localvolumeprovisioner
---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: localstorageclass
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: localstorageclass
    kubeaddons.mesosphere.com/provides: storageclass
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  cloudProvider:
    all: disabled
  manifest: |
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: local-path-provisioner-service-account
      namespace: kubeaddons
    ---
    apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    metadata:
      name: local-path-provisioner-role
      namespace: kubeaddons
    rules:
    - apiGroups: [""]
      resources: ["nodes", "persistentvolumeclaims"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["endpoints", "persistentvolumes", "pods"]
      verbs: ["*"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create", "patch"]
    - apiGroups: ["storage.k8s.io"]
      resources: ["storageclasses"]
      verbs: ["get", "list", "watch"]
    ---
    apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: local-path-provisioner-bind
      namespace: kubeaddons
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: local-path-provisioner-role
    subjects:
    - kind: ServiceAccount
      name: local-path-provisioner-service-account
      namespace: kubeaddons
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: local-path-config
      namespace: kubeaddons
    data:
      config.json: |-
        {"nodePathMap":[{
            "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
            "paths":["/opt/local-path-provisioner"]
        }]}
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: local-path-provisioner
      namespace: kubeaddons
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: local-path-provisioner
      template:
        metadata:
          labels:
            app: local-path-provisioner
        spec:
          serviceAccountName: local-path-provisioner-service-account
          containers:
          - name: local-path-provisioner
            image: rancher/local-path-provisioner:v0.0.5
            imagePullPolicy: Always
            command:
            - local-path-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
            volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
            env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumes:
            - name: config-volume
              configMap:
                name: local-path-config
    ---
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: local-path
      annotations:
        storageclass.beta.kubernetes.io/is-default-class: "false"
        kubernetes.io/description: Local default Storage class
    provisioner: rancher.io/local-path
    volumeBindingMode: WaitForFirstConsumer
