---
apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: prometheusadapter
  namespace: kubeaddons
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  chartReference:
    chart: stable/prometheus-adapter
    version: 1.0.2
    values: |
      ---
      prometheus:
        url: http://prometheus-kubeaddons-prom-prometheus
      metricsRelistInterval: 30s
