apiVersion: kubeaddons.mesosphere.io/v1alpha1
kind: Addon
metadata:
  name: traefik
  namespace: kubeaddons
spec:
  kubernetes:
    minSupportedVersion: v1.14.0
  chartReference:
    chart: stable/traefik
    version: 1.68.4
    values: |
      ---
      replicas: 2
      service:
        labels:
          servicemonitor.kubeaddons.mesosphere.io/path: "metrics"
      metrics:
        prometheus:
          enabled: true
      resources:
        limits:
          cpu: 2000m
        requests:
          cpu: 1000m
      rbac:
        enabled: true
      metrics:
        prometheus:
          enabled: true
      dashboard:
        enabled: true
        domain: traefik.localhost.localdomain
        serviceType: ClusterIP
      kubernetes:
        ingressEndpoint:
          publishedService: "kubeaddons/traefik-kubeaddons"
      ssl:
        enabled: true
        # TODO(mh): This temporarily switched off to get dex auth working without
        # TLS.
        enforced: false
        generateTLS: true
        defaultCN: traefik.localhost.localdomain
        defaultSANList:
          - "*"
